FROM golang:1.10-stretch

# add SSHD support to the base go container
RUN echo "root:Docker!" | chpasswd && \
apt-get update && \
apt-get install -y --no-install-recommends openssh-server curl nano wget && \
apt-get upgrade -y

WORKDIR /root
EXPOSE 2222 8080
ENV GOPATH=/root/m4

COPY sshd_config /etc/ssh/
COPY .bashrc /root
COPY runapp.sh /root


# get the code from git repo
RUN cd /root && \
git clone -b bartr https://github.com/bartr/m4  && \
cd /root/m4/src/m4/sampleapp && \
go get ./... && \
cd /root

CMD /root/runapp.sh
