FROM golang:1.10-stretch

# add SSHD support to the base go container
RUN echo "root:Docker!" | chpasswd && \
apt-get update && \
apt-get install -y --no-install-recommends openssh-server curl nano wget && \
apt-get upgrade -y && \
cd /root

WORKDIR /root

EXPOSE 2222 8080

COPY sshd_config /etc/ssh/
COPY .bashrc /root
COPY runapp.sh /root

# get the code from git repo
RUN cd /go/src && \
git clone -b eventgrid --single-branch https://github.com/bartr/m4  && \
go get ./... && \
cd /root

CMD /root/runapp.sh
