FROM alpine:latest

RUN mkdir -p /root

WORKDIR /root/

EXPOSE 8080

RUN apk --no-cache add ca-certificates

COPY sampleapp /root

ENV logpath /home/LogFiles/
ENV reqlogpath /home/LogFiles/

CMD /root/sampleapp logpath=${logpath} reqlogpath=${reqlogpath}


